steps:
- template: set-test-data-variables-step.yml

- task: CmdLine@2
  displayName: 'Download azcopy'
  inputs:
    script: |
      curl -so azcopy.tar.gz -L 'https://aka.ms/downloadazcopy-v10-mac'
      tar -zxvf azcopy.tar.gz --strip 1
    workingDirectory: $(Build.BinariesDirectory)

- task: PythonScript@0
  displayName: 'Download test data'
  inputs:
    scriptPath: '$(Build.SourcesDirectory)/tools/ci_build/github/download_test_data.py'
    arguments: --test_data_url $(TestDataUrl) --azure_region centralus --build_dir $(Build.BinariesDirectory)
    pythonInterpreter: '/usr/local/bin/python3'
    workingDirectory: $(Build.BinariesDirectory)
