# Defined as pipeline variables
# variables:
#   AgentPoolWin : 'Win-CPU'
#   AgentPoolLinux : 'Linux-CPU'
#   AgentPoolMacOS : 'macOS-10.13'

parameters:
  DoEsrp: 'false'

jobs: 
- template: ../../templates/win-ci.yml
  parameters:
    AgentPool : $(AgentPoolWin)
    JobName: 'Windows_CI_Dev'
    BuildCommand:  '$(Build.SourcesDirectory)\tools\ci_build\build.py --build_dir $(Build.BinariesDirectory) --skip_submodule_sync --cmake_path $(Build.BinariesDirectory)\cmake\bin\cmake.exe --ctest_path $(Build.BinariesDirectory)\cmake\bin\ctest.exe --use_mklml --build_shared_lib --build_csharp --enable_onnx_tests'
    DoDebugBuild: 'false'
    DoNugetPack : 'true'
    DoCompliance: 'false'
    DoEsrp: ${{ parameters.DoEsrp }}
    NuPackScript: |
     msbuild $(Build.SourcesDirectory)\csharp\OnnxRuntime.CSharp.proj /p:Configuration=RelWithDebInfo /t:CreatePackage /p:PackageId=Microsoft.ML.OnnxRuntime.MKLML
     copy $(Build.SourcesDirectory)\csharp\src\Microsoft.ML.OnnxRuntime\bin\RelWithDebInfo\*.nupkg $(Build.ArtifactStagingDirectory)

- template: ../../templates/linux-ci.yml
  parameters:
    AgentPool : $(AgentPoolLinux)
    JobName: 'Linux_CI_Dev'
    BuildCommand: 'tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -x " --use_mklml"'
    DoNugetPack : 'true'
    ZipDir : 'linux-x64'
    ArtifactName: 'drop-linux'
    NuPackScript: |
     set -e -x
     mkdir $(Build.BinariesDirectory)/linux-x64
     cp $(Build.BinariesDirectory)/Release/libonnxruntime.so $(Build.BinariesDirectory)/linux-x64
     cp $(Build.BinariesDirectory)/Release/mklml/src/project_mklml/lib/libiomp5.so $(Build.BinariesDirectory)/linux-x64
     cp $(Build.BinariesDirectory)/Release/mklml/src/project_mklml/lib/libmklml_intel.so $(Build.BinariesDirectory)/linux-x64
     ldd $(Build.BinariesDirectory)/linux-x64/libonnxruntime.so
     cd $(Build.BinariesDirectory)
     zip -r linux-x64.zip linux-x64
     cp $(Build.BinariesDirectory)/linux*.zip $(Build.ArtifactStagingDirectory)
     ls -al $(Build.ArtifactStagingDirectory)

- template: ../../templates/mac-ci.yml
  parameters:
    AgentPool : $(AgentPoolMacOS)
    JobName: 'MacOS_CI_Dev'
    BuildCommand: 'python3 $(Build.SourcesDirectory)/tools/ci_build/build.py --build_dir $(Build.BinariesDirectory) --skip_submodule_sync --parallel --build_shared_lib --use_mklml --enable_onnx_tests --config RelWithDebInfo'
    DoNugetPack : 'true'
    NuPackScript: |
     set -e -x
     mkdir $(Build.BinariesDirectory)/osx-x64
     find $(Build.BinariesDirectory)
     cp $(Build.BinariesDirectory)/RelWithDebInfo/libonnxruntime.dylib $(Build.BinariesDirectory)/osx-x64/
     cp $(Build.BinariesDirectory)/RelWithDebInfo/mklml/src/project_mklml/lib/libmklml.dylib $(Build.BinariesDirectory)/osx-x64/
     cp $(Build.BinariesDirectory)/RelWithDebInfo/mklml/src/project_mklml/lib/libiomp5.dylib $(Build.BinariesDirectory)/osx-x64/
     dsymutil $(Build.BinariesDirectory)/osx-x64/libonnxruntime.dylib -o $(Build.BinariesDirectory)/osx-x64/libonnxruntime.dylib.dSYM
     strip -S -x $(Build.BinariesDirectory)/osx-x64/libonnxruntime.dylib
     find $(Build.BinariesDirectory)/osx-x64 -ls
     install_name_tool -change "@rpath/libmklml.dylib" "@loader_path/libmklml.dylib" $(Build.BinariesDirectory)/osx-x64/libonnxruntime.dylib
     install_name_tool -change "@rpath/libiomp5.dylib" "@loader_path/libiomp5.dylib" $(Build.BinariesDirectory)/osx-x64/libmklml.dylib
     otool -L $(Build.BinariesDirectory)/osx-x64/libonnxruntime.dylib
     otool -L $(Build.BinariesDirectory)/osx-x64/libmklml.dylib
     otool -L $(Build.BinariesDirectory)/osx-x64/libiomp5.dylib
     cwd=`pwd`
     cd $(Build.BinariesDirectory)
     zip -r osx-x64.zip osx-x64
     cp $(Build.BinariesDirectory)/osx-x64.zip $(Build.ArtifactStagingDirectory)
     cd $cwd

- job: NuGet_Packaging
  pool: $(AgentPoolWin)
  dependsOn:
  - Windows_CI_Dev
  - Linux_CI_Dev
  - MacOS_CI_Dev
  condition: succeeded()
  steps:  
  - task: DownloadPipelineArtifact@0
    displayName: 'Download Pipeline Artifact - NuGet'
    inputs:
      artifactName: 'drop-nuget'
      targetPath: '$(Build.BinariesDirectory)/nuget-artifact'
    continueOnError: true

  - task: DownloadPipelineArtifact@0
    displayName: 'Download Pipeline Artifact - Linux'
    inputs:
      artifactName: 'drop-linux'
      targetPath: '$(Build.BinariesDirectory)/nuget-artifact'
    continueOnError: true

  - task: DownloadPipelineArtifact@0
    displayName: 'Download Pipeline Artifact - MacOS'
    inputs:
      artifactName: 'drop-osx'
      targetPath: '$(Build.BinariesDirectory)/nuget-artifact'
    continueOnError: true

  - script: |
     pushd $(Build.BinariesDirectory)\nuget-artifact
     dir
     powershell -Command "Invoke-WebRequest http://stahlworks.com/dev/unzip.exe -OutFile unzip.exe"
     powershell -Command "Invoke-WebRequest http://stahlworks.com/dev/zip.exe -OutFile zip.exe"
     set PATH=%CD%;%PATH%
     FOR /R %%i IN (*.nupkg) do ( 
         rename %%~ni.nupkg %%~ni.zip
         unzip %%~ni.zip -d %%~ni
         del /Q %%~ni.zip
         unzip linux-x64.zip -d linux-x64
         mkdir %%~ni\runtimes\linux-x64
         mkdir %%~ni\runtimes\linux-x64\native
         move linux-x64\linux-x64\libonnxruntime.so %%~ni\runtimes\linux-x64\native\libonnxruntime.so
         move linux-x64\linux-x64\libiomp5.so %%~ni\runtimes\linux-x64\native\libiomp5.so
         move linux-x64\linux-x64\libmklml_intel.so %%~ni\runtimes\linux-x64\native\libmklml_intel.so
         unzip osx-x64.zip -d osx-x64
         dir osx-x64 /s
         mkdir %%~ni\runtimes\osx-x64
         mkdir %%~ni\runtimes\osx-x64\native
         move osx-x64\osx-x64\libonnxruntime.dylib %%~ni\runtimes\osx-x64\native\libonnxruntime.dylib
         move osx-x64\osx-x64\libonnxruntime.dylib.dSYM %%~ni\runtimes\osx-x64\native\libonnxruntime.dylib.dSYM
         move osx-x64\osx-x64\libmklml.dylib %%~ni\runtimes\osx-x64\native\libmklml.dylib
         move osx-x64\osx-x64\libiomp5.dylib %%~ni\runtimes\osx-x64\native\libiomp5.dylib
         pushd %%~ni
         zip -r ..\%%~ni.zip .
         popd
         move %%~ni.zip %%~ni.nupkg
     )
     popd
     copy $(Build.BinariesDirectory)\nuget-artifact\*.nupkg $(Build.ArtifactStagingDirectory)
    displayName: 'Bundle NuGet and other binaries'

  - template: ../../templates/esrp_nuget.yml
    parameters:
      DisplayName: 'ESRP - sign NuGet package'
      FolderPath: '$(Build.ArtifactStagingDirectory)'
      DoEsrp: ${{ parameters.DoEsrp }}

  - task: PublishPipelineArtifact@0
    displayName: 'Publish Pipeline NuGet Artifact'
    inputs:
      artifactName: 'drop-signed-nuget'
      targetPath: '$(Build.ArtifactStagingDirectory)'

- template: test_all_os.yml
